name: Luacheck

concurrency:
  # for PR's cancel the running task, if another commit is pushed
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  # build on PR and push-to-master. This works for short-lived branches, and saves
  # CPU cycles on duplicated tests.
  # For long-lived branches that diverge, you'll want to run on all pushes, not
  # just on push-to-master.
  pull_request: {}
  push:
    branches:
    - master

jobs:

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: luarocks/gh-actions-lua@v11
      - uses: luarocks/gh-actions-luarocks@v6
      - name: dependencies
        run: make dev
      - name: Lint
        run: make lint
